//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Implementations.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Implementations.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя напрямую изменять поле &apos;{0}&apos;!.
        /// </summary>
        internal static string NonChangableField {
            get {
                return ResourceManager.GetString("NonChangableField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Записи не существует!.
        /// </summary>
        internal static string NotExist {
            get {
                return ResourceManager.GetString("NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно запустить в работу закак, у которого требуемая дата выполнения ({0}) меньше текущей даты ({1})!.
        /// </summary>
        internal static string OrderRequiredDateIsLessThanNow {
            get {
                return ResourceManager.GetString("OrderRequiredDateIsLessThanNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В заказе со статусом &apos;{0}&apos; нельзя ничего менять!.
        /// </summary>
        internal static string OrderWithStatusIsNonChangable {
            get {
                return ResourceManager.GetString("OrderWithStatusIsNonChangable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя удалить заказ со статусом &apos;{0}&apos;!.
        /// </summary>
        internal static string RemovingIsForbidden {
            get {
                return ResourceManager.GetString("RemovingIsForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разрешается изменять статус с &apos;New&apos; на &apos;InProgress&apos; и с &apos;InProgress&apos; на &apos;Done&apos;!.
        /// </summary>
        internal static string StatusMismatch {
            get {
                return ResourceManager.GetString("StatusMismatch", resourceCulture);
            }
        }
    }
}
